source: src
paths:
  uploads: uploads
  data: _data
  layouts: _includes
  includes: _includes
collections_config: 
  pages:
    path: ""
    filter: strict
    output: true
  posts:
    path: posts
    output: true
_inputs: {}
_select_data: {}
_structures: {}
_editables: {}
data_config: {}
timezone: Etc/UTC
